name: main
on:
  push:
    branches:
    - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit:${{ github.sha }}
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: Deploy the app
      run: |
        ls -l /
        cd /tmp
        echo "111"
        echo "git clone https://github.com/${{ secrets.GH_ORG }}/devspace-vcluster-argocd-prod.git"
        git clone https://github.com/${{ secrets.GH_ORG }}/devspace-vcluster-argocd-prod.git
        cd devspace-vcluster-argocd-prod
        cat production/devops-toolkit.yaml | sed -e "s@- ${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit:.*@- ${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit:${{ github.sha }}@g" | tee production/devops-toolkit.yaml
    #     cd kustomize/overlays/production
    #     kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit=${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit:$GITHUB_SHA
    #     kustomize build | kubectl apply --filename -
    #     kubectl --namespace production rollout status deployment devops-toolkit
 